project = gameduino-200a
vendor = xilinx
family = spartan3s
part = xc3s200a-4vq100
# part = xc3s200an-4ftg256
top_module = top
flashsize = 2048

vfiles = ../verilog/top.v ../verilog/fontrom.v

include xilinx.mk
